server:
  port: 8081
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/HMS
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970   # 256-bit hex
  access-token-expiration: 86400000        # 15 minutes
  refresh-token-expiration: 86400000